// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SubscriberID/subscriberID.proto

package SubscriberID

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubscriberId int32

const (
	SubscriberId_None   SubscriberId = 0
	SubscriberId_Normal SubscriberId = 100001
)

var SubscriberId_name = map[int32]string{
	0:      "None",
	100001: "Normal",
}

var SubscriberId_value = map[string]int32{
	"None":   0,
	"Normal": 100001,
}

func (x SubscriberId) String() string {
	return proto.EnumName(SubscriberId_name, int32(x))
}

func (SubscriberId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1d3e638f5fb3dd9c, []int{0}
}

func init() {
	proto.RegisterEnum("SubscriberID.SubscriberId", SubscriberId_name, SubscriberId_value)
}

func init() { proto.RegisterFile("SubscriberID/subscriberID.proto", fileDescriptor_1d3e638f5fb3dd9c) }

var fileDescriptor_1d3e638f5fb3dd9c = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x0f, 0x2e, 0x4d, 0x2a,
	0x4e, 0x2e, 0xca, 0x4c, 0x4a, 0x2d, 0xf2, 0x74, 0xd1, 0x2f, 0x46, 0xe2, 0xe8, 0x15, 0x14, 0xe5,
	0x97, 0xe4, 0x0b, 0xf1, 0x20, 0x2b, 0xd0, 0x52, 0xe3, 0x42, 0xe6, 0xa7, 0x08, 0x71, 0x70, 0xb1,
	0xf8, 0xe5, 0xe7, 0xa5, 0x0a, 0x30, 0x08, 0xf1, 0x70, 0xb1, 0xf9, 0xe5, 0x17, 0xe5, 0x26, 0xe6,
	0x08, 0x2c, 0xec, 0x65, 0x4b, 0x62, 0x03, 0x6b, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd1,
	0x49, 0x56, 0x3f, 0x5f, 0x00, 0x00, 0x00,
}
