// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ID/messageId.proto

package ID

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message int32

const (
	Message_None  Message = 0
	Message_Multi Message = 1
)

var Message_name = map[int32]string{
	0: "None",
	1: "Multi",
}

var Message_value = map[string]int32{
	"None":  0,
	"Multi": 1,
}

func (x Message) String() string {
	return proto.EnumName(Message_name, int32(x))
}

func (Message) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_40119fefa516e6a2, []int{0}
}

func init() {
	proto.RegisterEnum("ID.Message", Message_name, Message_value)
}

func init() { proto.RegisterFile("ID/messageId.proto", fileDescriptor_40119fefa516e6a2) }

var fileDescriptor_40119fefa516e6a2 = []byte{
	// 81 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xf2, 0x74, 0xd1, 0xcf,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xf5, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0xf2, 0x74, 0xd1, 0x92, 0xe3, 0x62, 0xf7, 0x85, 0x08, 0x0b, 0x71, 0x70, 0xb1, 0xf8, 0xe5, 0xe7,
	0xa5, 0x0a, 0x30, 0x08, 0x71, 0x72, 0xb1, 0xfa, 0x96, 0xe6, 0x94, 0x64, 0x0a, 0x30, 0x26, 0xb1,
	0x81, 0x95, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x94, 0x97, 0x32, 0x40, 0x00, 0x00,
	0x00,
}
